version: '3.7'
services:
  app:
    container_name: go_api_hackathon
    image: go_api_hackathon
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
      args:
          - repo_user=eldhoral
          - repo_token=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
          - repo_url=github.com
          - repo_organization=garuda-hacks
          - app_name=api_hackathon
    volumes: 
      - .:/app
    ports: 
      - 8080:8080
    networks: 
      - backend
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: go_hackathon_database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5431:5434
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
    networks:
      - backend


volumes:
  pkg:
    driver: local
  db-data:
    driver: local

networks:
  backend:
    driver: bridge